"""
CodeSearch Agent
================

This agent answers questions about the project's own source code.
It uses a WorkspaceContextProvider — a pattern that wraps a read-only
workspace toolkit behind a sub-agent. The parent agent sees a single
`query_my_codebase(question)` tool, while the sub-agent handles the
details of listing, searching, and reading files.
"""

# Path is used to resolve the repository root directory so the context
# provider knows which folder to make searchable.
from pathlib import Path

# Agent is the core class from Agno. Every agent you create is an
# instance of this class — it bundles a model, tools, instructions,
# and persistence into one object.
from agno.agent import Agent

# WorkspaceContextProvider is a special Agno helper that creates a
# sub-agent with read-only access to a directory tree. Instead of
# giving the main agent many low-level tools (list, search, read),
# it exposes one high-level `query_<id>` tool that delegates to the
# sub-agent. This keeps the main agent focused and reduces prompt
# clutter.
from agno.context.workspace import WorkspaceContextProvider

# default_model() is our project-wide factory that returns a fresh model
# instance. We use it everywhere so changing the model is a one-line edit.
from app.settings import default_model

# get_db() returns the database backend (Postgres or SQLite) that stores
# agent sessions, memory, and metrics. Every agent needs one.
from db import get_db

# Resolve the repository root by going up one directory from this file.
# __file__ is .../agents/code_search.py, so parents[1] is the repo root.
# This tells the WorkspaceContextProvider where the codebase lives.
REPO_ROOT = Path(__file__).resolve().parents[1]

# ── WorkspaceContextProvider ──────────────────────────────────────────
# This creates a sub-agent that can list, search, and read files inside
# REPO_ROOT. The main agent doesn't see those tools directly — instead
# it gets a single `query_my_codebase(question)` tool that hands off to
# the sub-agent. This "context provider" pattern is ideal when you want
# one-source agents and want to collapse many tools into one to keep
# the model focused.
#
#   id    — used to name the generated tool: `query_my_codebase`
#   name  — human-readable label for the sub-agent
#   root  — the directory tree the sub-agent can read
#   model — the LLM powering the sub-agent (separate from the parent)
codebase_context = WorkspaceContextProvider(
    id="my-codebase",
    name="My Codebase",
    root=REPO_ROOT,
    model=default_model(),
)


CODE_SEARCH_INSTRUCTIONS = """\
You answer questions about your own codebase. Be specific and concrete:
quote real file paths and line numbers from the codebase, never guess.
If a question is off-topic or not answered by the project's files, say
so plainly and offer to take a codebase question instead.
"""


# ── Agent definition ──────────────────────────────────────────────────
# This is where the agent is assembled. Each parameter controls a
# different aspect of the agent's behaviour:
#
#   id              — unique identifier used in URLs, logs, and the
#                    AgentOS dashboard. Must be URL-safe (kebab-case).
#   name            — human-readable name shown in the UI.
#   model           — the LLM that powers the agent. default_model()
#                    returns a fresh Ollama instance so agents don't
#                    share mutable state.
#   db              — where sessions, memory, and metrics are stored.
#                    get_db() picks Postgres or SQLite based on env.
#   tools           — codebase_context.get_tools() returns the list of
#                    tools generated by the context provider. In this
#                    case, a single `query_my_codebase` tool.
#   instructions    — the system prompt. We combine our own instructions
#                    with codebase_context.instructions(), which adds
#                    context about the workspace structure so the agent
#                    knows what it can search.
#   enable_agentic_memory
#                    — lets the agent remember facts across sessions.
#   add_datetime_to_context
#                    — injects the current date/time into the prompt.
#   add_history_to_context
#                    — includes previous conversation turns so the
#                    agent can refer back to earlier messages.
#   num_history_runs — how many past runs (full conversations) to
#                    include. 5 gives the agent a longer memory of
#                    prior interactions.
#   markdown        — tells the agent to format responses in Markdown.
code_search = Agent(
    id="code-search",
    name="CodeSearch",
    model=default_model(),
    db=get_db(),
    tools=codebase_context.get_tools(),
    instructions=CODE_SEARCH_INSTRUCTIONS + "\n\n" + codebase_context.instructions(),
    enable_agentic_memory=True,
    add_datetime_to_context=True,
    add_history_to_context=True,
    num_history_runs=5,
    markdown=True,
)
